--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/usr/share/endeavouros/backgrounds/greenhouse.png"

-- Special
background="#37152f"
foreground="#f5debf"
cursor="#f5debf"

-- Colors
color0="#37152f"
color1="#FFD57C"
color2="#7B6B87"
color3="#9D7485"
color4="#B49691"
color5="#D6A794"
color6="#EEB596"
color7="#f5debf"
color8="#ab9b85"
color9="#FFD57C"
color10="#7B6B87"
color11="#9D7485"
color12="#B49691"
color13="#D6A794"
color14="#EEB596"
color15="#f5debf"
