# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/endeavouros/backgrounds/greenhouse.png'

# Special
background='#37152f'
foreground='#f5debf'
cursor='#f5debf'

# Colors
color0='#37152f'
color1='#FFD57C'
color2='#7B6B87'
color3='#9D7485'
color4='#B49691'
color5='#D6A794'
color6='#EEB596'
color7='#f5debf'
color8='#ab9b85'
color9='#FFD57C'
color10='#7B6B87'
color11='#9D7485'
color12='#B49691'
color13='#D6A794'
color14='#EEB596'
color15='#f5debf'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
