# Shell variables
# Generated by 'wal'
wallpaper='/usr/share/backgrounds/lofi-late-night-coffee-shop-2-1366×768.png'

# Special
background='#0d1215'
foreground='#9bc1dd'
cursor='#9bc1dd'

# Colors
color0='#0d1215'
color1='#575966'
color2='#A45A4E'
color3='#708466'
color4='#B0936C'
color5='#DBA069'
color6='#2E5399'
color7='#9bc1dd'
color8='#6c879a'
color9='#575966'
color10='#A45A4E'
color11='#708466'
color12='#B0936C'
color13='#DBA069'
color14='#2E5399'
color15='#9bc1dd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
